component_list = [
  "./tools/bass-o-matic --workspace=./ --components=paths | sed -e 's;./components/;;'"
]
metadata_generation_script = [
  "gmake generate-pakage-kdl"
]
change_to_component_dir = true
